languageCode = "en"
title = "Markus Oberlehner"
baseURL = "https://markus.oberlehner.net/"
enableRobotsTXT = true
SectionPagesMenu = "main"
disableHugoGeneratorInject = true
PygmentsCodeFences = true
PygmentsUseClasses = true

[params]
  description = "Read articles about Web Development topics like JavaScript, CSS, TDD and Front-End Architecture but also about Motivation and Investing."
  author = "Markus Oberlehner"

[[menu.main]]
    name = "Home"
    weight = -100
    identifier = "home"
    url = "/"
