languageCode = "en"
title = "Markus Oberlehner"
baseURL = "https://markus.oberlehner.net/"
enableRobotsTXT = true
SectionPagesMenu = "main"
disableHugoGeneratorInject = true
PygmentsCodeFences = true
PygmentsUseClasses = true

[params]
  description = "Articles about Web Development topics like JavaScript, CSS, Test Driven Development and Front-End Architecture but also about general life issues like Motivation and Investing."
  author = "Markus Oberlehner"

[[menu.main]]
    name = "Home"
    weight = -100
    identifier = "home"
    url = "/"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"
  lego = "lego"
